# Generated by Django 4.2.5 on 2023-10-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания задачи')),
                ('deadline_date', models.DateTimeField(verbose_name='Дата-дедлайн задачи')),
                ('priority', models.CharField(choices=[('low', 'Малый'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=6, verbose_name='Уровень приоритета')),
                ('status', models.CharField(choices=[('not_done', 'Не выполнено'), ('done', 'Выполнено')], default='not_done', max_length=9, verbose_name='Статус')),
            ],
        ),
    ]
